/**
 * This file is auto-generated by scripts/bundle-locales.mjs, based on the contents of the src/locales/ directory.
 * Any manual changes in here will be overwritten on build!
 */
import enAutofill from './en/autofill.json'
import xaAutofill from './xa/autofill.json'

export default {
    en: { autofill: enAutofill },
    xa: { autofill: xaAutofill }
}
