/**
 * This file is auto-generated by scripts/bundle-locales.mjs, based on the contents of the src/locales/ directory.
 * Any manual changes in here will be overwritten on build!
 */
import bgAutofill from './bg/autofill.json';
import csAutofill from './cs/autofill.json';
import daAutofill from './da/autofill.json';
import deAutofill from './de/autofill.json';
import elAutofill from './el/autofill.json';
import enAutofill from './en/autofill.json';
import esAutofill from './es/autofill.json';
import etAutofill from './et/autofill.json';
import fiAutofill from './fi/autofill.json';
import frAutofill from './fr/autofill.json';
import hrAutofill from './hr/autofill.json';
import huAutofill from './hu/autofill.json';
import itAutofill from './it/autofill.json';
import ltAutofill from './lt/autofill.json';
import lvAutofill from './lv/autofill.json';
import nbAutofill from './nb/autofill.json';
import nlAutofill from './nl/autofill.json';
import plAutofill from './pl/autofill.json';
import ptAutofill from './pt/autofill.json';
import roAutofill from './ro/autofill.json';
import ruAutofill from './ru/autofill.json';
import skAutofill from './sk/autofill.json';
import slAutofill from './sl/autofill.json';
import svAutofill from './sv/autofill.json';
import trAutofill from './tr/autofill.json';
import xaAutofill from './xa/autofill.json';

export default {
    bg: { autofill: bgAutofill },
    cs: { autofill: csAutofill },
    da: { autofill: daAutofill },
    de: { autofill: deAutofill },
    el: { autofill: elAutofill },
    en: { autofill: enAutofill },
    es: { autofill: esAutofill },
    et: { autofill: etAutofill },
    fi: { autofill: fiAutofill },
    fr: { autofill: frAutofill },
    hr: { autofill: hrAutofill },
    hu: { autofill: huAutofill },
    it: { autofill: itAutofill },
    lt: { autofill: ltAutofill },
    lv: { autofill: lvAutofill },
    nb: { autofill: nbAutofill },
    nl: { autofill: nlAutofill },
    pl: { autofill: plAutofill },
    pt: { autofill: ptAutofill },
    ro: { autofill: roAutofill },
    ru: { autofill: ruAutofill },
    sk: { autofill: skAutofill },
    sl: { autofill: slAutofill },
    sv: { autofill: svAutofill },
    tr: { autofill: trAutofill },
    xa: { autofill: xaAutofill },
};
