/* DO NOT EDIT, this file was generated by scripts/api-call-generator.js */
import {
    getAutofillDataRequestSchema,
    getAutofillDataResponseSchema,
    getRuntimeConfigurationResponseSchema,
    storeFormDataSchema,
    getAvailableInputTypesResultSchema,
    getAutofillInitDataResponseSchema,
    getAutofillCredentialsParamsSchema,
    getAutofillCredentialsResultSchema,
    setSizeParamsSchema,
    selectedDetailParamsSchema,
    askToUnlockProviderResultSchema,
    checkCredentialsProviderStatusResultSchema,
    sendJSPixelParamsSchema,
    storeUserDataParamsSchema,
    getIsLoggedInResultSchema,
    getUserDataResultSchema,
    getEmailProtectionCapabilitiesResultSchema,
    getAddressesResultSchema,
    refreshAliasResultSchema
} from "./validators.zod.js"
import { DeviceApiCall } from "../../../packages/device-api";

/**
 * @extends {DeviceApiCall<getAutofillDataRequestSchema, getAutofillDataResponseSchema>} 
 */
export class GetAutofillDataCall extends DeviceApiCall {
  method = "getAutofillData"
  id = "getAutofillDataResponse"
  paramsValidator = getAutofillDataRequestSchema
  resultValidator = getAutofillDataResponseSchema
}
/**
 * @extends {DeviceApiCall<any, getRuntimeConfigurationResponseSchema>} 
 */
export class GetRuntimeConfigurationCall extends DeviceApiCall {
  method = "getRuntimeConfiguration"
  id = "getRuntimeConfigurationResponse"
  resultValidator = getRuntimeConfigurationResponseSchema
}
/**
 * @extends {DeviceApiCall<storeFormDataSchema, any>} 
 */
export class StoreFormDataCall extends DeviceApiCall {
  method = "storeFormData"
  paramsValidator = storeFormDataSchema
}
/**
 * @extends {DeviceApiCall<any, getAvailableInputTypesResultSchema>} 
 */
export class GetAvailableInputTypesCall extends DeviceApiCall {
  method = "getAvailableInputTypes"
  id = "getAvailableInputTypesResponse"
  resultValidator = getAvailableInputTypesResultSchema
}
/**
 * @extends {DeviceApiCall<any, getAutofillInitDataResponseSchema>} 
 */
export class GetAutofillInitDataCall extends DeviceApiCall {
  method = "getAutofillInitData"
  id = "getAutofillInitDataResponse"
  resultValidator = getAutofillInitDataResponseSchema
}
/**
 * @extends {DeviceApiCall<getAutofillCredentialsParamsSchema, getAutofillCredentialsResultSchema>} 
 */
export class GetAutofillCredentialsCall extends DeviceApiCall {
  method = "getAutofillCredentials"
  id = "getAutofillCredentialsResponse"
  paramsValidator = getAutofillCredentialsParamsSchema
  resultValidator = getAutofillCredentialsResultSchema
}
/**
 * @extends {DeviceApiCall<setSizeParamsSchema, any>} 
 */
export class SetSizeCall extends DeviceApiCall {
  method = "setSize"
  paramsValidator = setSizeParamsSchema
}
/**
 * @extends {DeviceApiCall<selectedDetailParamsSchema, any>} 
 */
export class SelectedDetailCall extends DeviceApiCall {
  method = "selectedDetail"
  paramsValidator = selectedDetailParamsSchema
}
/**
 * @extends {DeviceApiCall<any, any>} 
 */
export class CloseAutofillParentCall extends DeviceApiCall {
  method = "closeAutofillParent"
}
/**
 * @extends {DeviceApiCall<any, askToUnlockProviderResultSchema>} 
 */
export class AskToUnlockProviderCall extends DeviceApiCall {
  method = "askToUnlockProvider"
  id = "askToUnlockProviderResponse"
  resultValidator = askToUnlockProviderResultSchema
}
/**
 * @extends {DeviceApiCall<any, checkCredentialsProviderStatusResultSchema>} 
 */
export class CheckCredentialsProviderStatusCall extends DeviceApiCall {
  method = "checkCredentialsProviderStatus"
  id = "checkCredentialsProviderStatusResponse"
  resultValidator = checkCredentialsProviderStatusResultSchema
}
/**
 * @extends {DeviceApiCall<sendJSPixelParamsSchema, any>} 
 */
export class SendJSPixelCall extends DeviceApiCall {
  method = "sendJSPixel"
  paramsValidator = sendJSPixelParamsSchema
}
/**
 * @extends {DeviceApiCall<storeUserDataParamsSchema, any>} 
 */
export class StoreUserDataCall extends DeviceApiCall {
  method = "storeUserData"
  id = "storeUserDataResponse"
  paramsValidator = storeUserDataParamsSchema
}
/**
 * @extends {DeviceApiCall<any, any>} 
 */
export class RemoveUserDataCall extends DeviceApiCall {
  method = "removeUserData"
}
/**
 * @extends {DeviceApiCall<any, getIsLoggedInResultSchema>} 
 */
export class GetIsLoggedInCall extends DeviceApiCall {
  method = "getIsLoggedIn"
  id = "getIsLoggedInResponse"
  resultValidator = getIsLoggedInResultSchema
}
/**
 * @extends {DeviceApiCall<any, getUserDataResultSchema>} 
 */
export class GetUserDataCall extends DeviceApiCall {
  method = "getUserData"
  id = "getUserDataResponse"
  resultValidator = getUserDataResultSchema
}
/**
 * @extends {DeviceApiCall<any, getEmailProtectionCapabilitiesResultSchema>} 
 */
export class GetEmailProtectionCapabilitiesCall extends DeviceApiCall {
  method = "getEmailProtectionCapabilities"
  id = "getEmailProtectionCapabilitiesResponse"
  resultValidator = getEmailProtectionCapabilitiesResultSchema
}
/**
 * @extends {DeviceApiCall<any, getAddressesResultSchema>} 
 */
export class GetAddressesCall extends DeviceApiCall {
  method = "getAddresses"
  id = "getAddressesResponse"
  resultValidator = getAddressesResultSchema
}
/**
 * @extends {DeviceApiCall<any, refreshAliasResultSchema>} 
 */
export class RefreshAliasCall extends DeviceApiCall {
  method = "refreshAlias"
  id = "refreshAliasResponse"
  resultValidator = refreshAliasResultSchema
}