/* DO NOT EDIT, this file was generated by scripts/api-call-generator.js */
// getAlias.params.json

export interface GetAliasParams {
  requiresUserPermission: boolean;
  shouldConsumeAliasIfProvided: boolean;
}

// getAlias.result.json

export interface GetAliasResult {
  success: {
    alias: string;
  };
}
