name: Autofill Release Workflow

on:
    release:
        types: [created]
    workflow_dispatch:
        inputs:
            tag_name:
                description: 'Tag name for the release'
                required: true
            release_url:
                description: 'URL for the release'
                required: true
            release_notes:
                description: 'Release notes for the release'
                required: true

env:
    VERSION: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
    RELEASE_URL: ${{ github.event.inputs.release_url || github.event.release.html_url }}
    RELEASE_NOTES: ${{ github.event.inputs.release_notes || github.event.release.body }}

jobs:
    # ------------------------------------------------------------------------------
    # Create initial Asana subtasks
    # ------------------------------------------------------------------------------
    create_asana_tasks:
        runs-on: ubuntu-20.04
        outputs:
            asana-output: ${{ steps.create-asana-tasks.outputs.ASANA_OUTPUT }}
        steps:
            # --- Setup ---
            - uses: actions/checkout@v3
              with:
                  path: autofill/
            - uses: ./autofill/.github/actions/setup-release-scripts
            # --- Effect ---
            - name: Create Asana Tasks
              id: create-asana-tasks
              env:
                  ASANA_ACCESS_TOKEN: ${{ secrets.NATIVE_APPS_WORKFLOW }}
              run: |
                  JSON_STRING="$(node ./autofill/scripts/release/asana-create-tasks.js)"
                  echo "ASANA_OUTPUT=$JSON_STRING" >> $GITHUB_OUTPUT

    # ------------------------------------------------------------------------------
    # Create PR with updated autofill on Android
    # ------------------------------------------------------------------------------

    update_android:
        if: false # TODO: Remove after testing monorepo release changes
        runs-on: ubuntu-20.04
        outputs:
            pull-request-url: ${{ steps.create-pr.outputs.pull-request-url }}
        needs: create_asana_tasks
        steps:
            # --- Setup ---
            - uses: actions/checkout@v3
              with:
                  path: autofill/
            - uses: ./autofill/.github/actions/setup-release-scripts
            # --- Action ---
            - name: Checkout Android
              uses: actions/checkout@v3
              with:
                  repository: duckduckgo/android
                  path: android/
                  token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
            - uses: actions/setup-node@v3
              with:
                  node-version: current
            - name: Update Android autofill reference
              run: |
                  cd android
                  npm install github:duckduckgo/duckduckgo-autofill#${{ env.VERSION }}
                  cd ..
            - name: Create Android PR Body
              env:
                  ASANA_OUTPUT: ${{ needs.create_asana_tasks.outputs.asana-output }}
              run: |
                  TEMPLATE="$(node ./autofill/scripts/release/create-pr-template.js android)"
                  # Creates a randomised delimiter. See https://app.asana.com/0/1199892415909552/1203243297643584/f
                  DELIMITER=$(echo $RANDOM | md5sum | head -c 20;)
                  echo "PR_BODY_ANDROID<<$DELIMITER" >> $GITHUB_ENV
                  echo "$TEMPLATE" >> $GITHUB_ENV
                  echo "$DELIMITER" >> $GITHUB_ENV
            # --- Effect ---
            - name: Create PR for Android
              uses: peter-evans/create-pull-request@b3a2c5d525a1eb75e75c781e45a1bf3bfc23bdc6
              id: create-pr
              with:
                  path: android/
                  add-paths: |
                      package.json
                      package-lock.json
                      node_modules/@duckduckgo/autofill
                  commit-message: Update autofill to ${{ env.VERSION }}
                  branch: update-autofill-${{ env.VERSION }}
                  title: Update autofill to ${{ env.VERSION }}
                  body: '${{ env.PR_BODY_ANDROID }}'
                  token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}

    # ------------------------------------------------------------------------------
    # Create PR with updated autofill on Apple platforms
    # ------------------------------------------------------------------------------

    update_apple:
        runs-on: ubuntu-20.04
        outputs:
            pull-request-url: ${{ steps.create-pr.outputs.pull-request-url }}
            pull-request-head-sha: ${{ steps.create-pr.outputs.pull-request-head-sha }}
        needs: create_asana_tasks
        steps:
            # --- Setup ---
            - uses: actions/checkout@v3
              with:
                  path: autofill/
            - uses: ./autofill/.github/actions/setup-release-scripts
            # --- Action ---
            - name: Checkout Apple monorepo
              uses: actions/checkout@v3
              with:
                  repository: duckduckgo/apple-monorepo-test # TODO: Update with final monorepo URL
                  path: apple-monorepo/
                  token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
            - name: Update Apple autofill reference
              run: |
                  node ./autofill/scripts/release/update-bsk-repo.js
            - name: Create Apple PR Body
              env:
                  ASANA_OUTPUT: ${{ needs.create_asana_tasks.outputs.asana-output }}
              run: |
                  TEMPLATE="$(node ./autofill/scripts/release/create-pr-template.js apple)"
                  # Creates a randomised delimiter. See https://app.asana.com/0/1199892415909552/1203243297643584/f
                  DELIMITER=$(echo $RANDOM | md5sum | head -c 20;)
                  echo "PR_BODY_APPLE<<$DELIMITER" >> $GITHUB_ENV
                  echo "$TEMPLATE" >> $GITHUB_ENV
                  echo "$DELIMITER" >> $GITHUB_ENV
            # --- Effect ---
            - name: Create PR for Apple monorepo
              uses: peter-evans/create-pull-request@b3a2c5d525a1eb75e75c781e45a1bf3bfc23bdc6
              id: create-pr
              with:
                  path: apple-monorepo/
                  add-paths: BrowserServicesKit/Package.swift,BrowserServicesKit/Package.resolved
                  commit-message: Update autofill to ${{ env.VERSION }}
                  branch: update-autofill-${{ env.VERSION }}
                  title: Update autofill to ${{ env.VERSION }}
                  body: ${{ env.PR_BODY_APPLE }}
                  token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}

    # ------------------------------------------------------------------------------
    # Create PR with updated autofill on Browser extensions
    # ------------------------------------------------------------------------------

    update_extensions:
        if: false # TODO: Remove after testing monorepo release changes
        runs-on: ubuntu-20.04
        outputs:
            pull-request-url: ${{ steps.create-pr.outputs.pull-request-url }}
        needs: create_asana_tasks
        steps:
            # --- Setup ---
            - uses: actions/checkout@v3
              with:
                  path: autofill/
            - uses: ./autofill/.github/actions/setup-release-scripts
            # --- Action ---
            - name: Checkout Extensions
              uses: actions/checkout@v3
              with:
                  repository: duckduckgo/duckduckgo-privacy-extension
                  path: extensions/
                  token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
            - uses: actions/setup-node@v3
              with:
                  node-version-file: 'extensions/.nvmrc'
            - name: Update Extensions autofill reference
              run: |
                  cd extensions
                  npm install github:duckduckgo/duckduckgo-autofill#${{ env.VERSION }}
                  cd ..
            - name: Create Extensions PR Body
              env:
                  ASANA_OUTPUT: ${{ needs.create_asana_tasks.outputs.asana-output }}
              run: |
                  TEMPLATE="$(node ./autofill/scripts/release/create-pr-template.js extensions)"
                  # Creates a randomised delimiter. See https://app.asana.com/0/1199892415909552/1203243297643584/f
                  DELIMITER=$(echo $RANDOM | md5sum | head -c 20;)
                  echo "PR_BODY_EXTENSIONS<<$DELIMITER" >> $GITHUB_ENV
                  echo "$TEMPLATE" >> $GITHUB_ENV
                  echo "$DELIMITER" >> $GITHUB_ENV
            # --- Effect ---
            - name: Create PR for Extensions
              uses: peter-evans/create-pull-request@b3a2c5d525a1eb75e75c781e45a1bf3bfc23bdc6
              id: create-pr
              with:
                  path: extensions/
                  add-paths: |
                      package.json
                      package-lock.json
                  commit-message: Update autofill to ${{ env.VERSION }}
                  branch: update-autofill-${{ env.VERSION }}
                  title: Update autofill to ${{ env.VERSION }}
                  body: '${{ env.PR_BODY_EXTENSIONS }}'
                  token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}

    # ------------------------------------------------------------------------------
    # Create PR with updated autofill on Windows
    # ------------------------------------------------------------------------------

    update_windows:
        if: false # TODO: Remove after testing monorepo release changes
        runs-on: ubuntu-20.04
        outputs:
            pull-request-url: ${{ steps.create-pr.outputs.pull-request-url }}
        needs: create_asana_tasks
        steps:
            # --- Setup ---
            - uses: actions/checkout@v3
              with:
                  path: autofill/
            - uses: ./autofill/.github/actions/setup-release-scripts
            # --- Action ---
            - name: Checkout Windows
              uses: actions/checkout@v3
              with:
                  repository: duckduckgo/windows-browser
                  path: windows/
                  submodules: true
                  token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
            - name: Update Windows autofill reference
              run: |
                  cd windows/submodules/duckduckgo-autofill
                  git fetch --tags
                  git checkout ${{ env.VERSION }}
                  cd ../../../
            - name: Create Windows PR Body
              env:
                  ASANA_OUTPUT: ${{ needs.create_asana_tasks.outputs.asana-output }}
              run: |
                  TEMPLATE="$(node ./autofill/scripts/release/create-pr-template.js windows)"
                  # Creates a randomised delimiter. See https://app.asana.com/0/1199892415909552/1203243297643584/f
                  DELIMITER=$(echo $RANDOM | md5sum | head -c 20;)
                  echo "PR_BODY_WINDOWS<<$DELIMITER" >> $GITHUB_ENV
                  echo "$TEMPLATE" >> $GITHUB_ENV
                  echo "$DELIMITER" >> $GITHUB_ENV
            # --- Effect ---
            - name: Create PR for Windows
              uses: peter-evans/create-pull-request@b3a2c5d525a1eb75e75c781e45a1bf3bfc23bdc6
              id: create-pr
              with:
                  path: windows/
                  add-paths: |
                      submodules/duckduckgo-autofill
                  commit-message: Update autofill to ${{ env.VERSION }}
                  branch: update-autofill-${{ env.VERSION }}
                  title: Update autofill to ${{ env.VERSION }}
                  body: '${{ env.PR_BODY_WINDOWS }}'
                  token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}

    # ------------------------------------------------------------------------------
    # Update Asana subtasks with PR URLs
    # ------------------------------------------------------------------------------

    update_asana_tasks:
        runs-on: ubuntu-20.04
        # Always run this final step, even if any of the updates have failed
        # unless the previous jobs were cancelled
        if: ${{ always() && !contains(needs.*.result, 'cancelled') }}
        needs: [create_asana_tasks, update_apple, update_android, update_extensions, update_windows]
        steps:
            # --- Setup ---
            - uses: actions/checkout@v3
              with:
                  path: autofill/
            - uses: ./autofill/.github/actions/setup-release-scripts
            # --- Effect ---
            - name: Update Asana tasks
              env:
                  ASANA_ACCESS_TOKEN: ${{ secrets.NATIVE_APPS_WORKFLOW }}
                  ASANA_OUTPUT: ${{ needs.create_asana_tasks.outputs.asana-output }}
                  APPLE_PR_URL: ${{ needs.update_apple.outputs.pull-request-url }}
                  ANDROID_PR_URL: ${{ needs.update_android.outputs.pull-request-url }}
                  WINDOWS_PR_URL: ${{ needs.update_windows.outputs.pull-request-url }}
              run: |
                  node ./autofill/scripts/release/asana-update-tasks.js

            - name: Ouput workflow summary
              # Show failure message if any of the jobs report failed
              if: ${{ contains(needs.*.result, 'failure') }}
              run: |
                  echo "Release process completed but with failures reported." >> $GITHUB_STEP_SUMMARY
                  echo "Please review the job output to see which steps require manual intervention." >> $GITHUB_STEP_SUMMARY
            - name: Ouput workflow summary
              # Show success message as long as none of the jobs report failed
              if: ${{ !contains(needs.*.result, 'failure') }}
              run: |
                  echo "Release process completed successfully." >> $GITHUB_STEP_SUMMARY
                  echo "All PRs and Asana tasks created! :rocket:" >> $GITHUB_STEP_SUMMARY
