name: Autofill Release Workflow

on:
  release:
    types: [ created ]

jobs:
  autofill_release: # TODO: rename the file to autofill-release.yml once reviewed to keep a clear diff
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          path: autofill/
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'autofill/.nvmrc'

      - name: Create Asana Tasks
        id: create-asana-tasks
        env:
          ASANA_ACCESS_TOKEN: ${{ secrets.NATIVE_APPS_WORKFLOW }}
          VERSION: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES: ${{ github.event.release.body }}
        run: |
          cd autofill
          npm install
          JSON_STRING="$(node ./scripts/release/asana-create-tasks.js)"
          echo "ASANA_OUTPUT=$JSON_STRING" >> $GITHUB_OUTPUT
          cd ..

      - name: Checkout Android
        uses: actions/checkout@v3
        with:
          repository: duckduckgo/android
          path: android/
          ref: develop
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
      - name: Update Android autofill reference
        run: |
          cd android
          npm install github:duckduckgo/duckduckgo-autofill#${{ github.event.release.tag_name }}
          cd ..
      - name: Create Android PR Body
        env:
          VERSION: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES: ${{ github.event.release.body }}
          ASANA_OUTPUT: ${{ steps.create-asana-tasks.outputs.ASANA_OUTPUT }}
        run: |
          TEMPLATE="$(node ./autofill/scripts/release/create-pr-template.js android)"
          # Creates a randomised delimiter. See https://app.asana.com/0/1199892415909552/1203243297643584/f
          DELIMITER=$(echo $RANDOM | md5sum | head -c 20;)
          echo "PR_BODY_ANDROID<<$DELIMITER" >> $GITHUB_ENV
          echo "$TEMPLATE" >> $GITHUB_ENV
          echo "$DELIMITER" >> $GITHUB_ENV
      - name: Create PR for Android
        uses: peter-evans/create-pull-request@88bf0de51c7487d91e1abbb4899332e602c58bbf
        id: android-pr
        with:
          path: android/
          add-paths: |
            package.json
            package-lock.json
            node_modules/@duckduckgo/autofill
          commit-message: Update autofill to ${{ github.event.release.tag_name }}
          branch: update-autofill-${{ github.event.release.tag_name }}
          title: Update autofill to ${{ github.event.release.tag_name }}
          body: "${{ env.PR_BODY_ANDROID }}"
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}

      - name: Checkout BSK
        uses: actions/checkout@v3
        with:
          repository: duckduckgo/BrowserServicesKit
          path: bsk/
          ref: main
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
      - name: Update BSK autofill reference
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          node ./autofill/scripts/release/update-bsk-repo.js
      - name: Create BSK PR Body
        env:
          VERSION: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES: ${{ github.event.release.body }}
          ASANA_OUTPUT: ${{ steps.create-asana-tasks.outputs.ASANA_OUTPUT }}
        run: |
          TEMPLATE="$(node ./autofill/scripts/release/create-pr-template.js bsk)"
          # Creates a randomised delimiter. See https://app.asana.com/0/1199892415909552/1203243297643584/f
          DELIMITER=$(echo $RANDOM | md5sum | head -c 20;)
          echo "PR_BODY_BSK<<$DELIMITER" >> $GITHUB_ENV
          echo "$TEMPLATE" >> $GITHUB_ENV
          echo "$DELIMITER" >> $GITHUB_ENV
      - name: Create PR for BSK
        uses: peter-evans/create-pull-request@88bf0de51c7487d91e1abbb4899332e602c58bbf
        id: bsk-pr
        with:
          path: bsk/
          add-paths: Package.swift,Package.resolved
          commit-message: Update autofill to ${{ github.event.release.tag_name }}
          branch: update-autofill-${{ github.event.release.tag_name }}
          title: Update autofill to ${{ github.event.release.tag_name }}
          body: ${{ env.PR_BODY_BSK }}
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}

      - name: Checkout iOS
        uses: actions/checkout@v3
        with:
          repository: duckduckgo/iOS
          path: ios/
          ref: develop
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
      - name: Update iOS autofill reference
        env:
          BSK_SHA: ${{ steps.bsk-pr.outputs.pull-request-head-sha }}
        run: |
          node ./autofill/scripts/release/update-apple-device-repo.js 'ios'
      - name: Create iOS PR Body
        env:
          VERSION: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES: ${{ github.event.release.body }}
          ASANA_OUTPUT: ${{ steps.create-asana-tasks.outputs.ASANA_OUTPUT }}
          BSK_PR_URL: ${{ steps.bsk-pr.outputs.pull-request-url }}
        run: |
          TEMPLATE="$(node ./autofill/scripts/release/create-pr-template.js ios)"
          # Creates a randomised delimiter. See https://app.asana.com/0/1199892415909552/1203243297643584/f
          DELIMITER=$(echo $RANDOM | md5sum | head -c 20;)
          echo "PR_BODY_IOS<<$DELIMITER" >> $GITHUB_ENV
          echo "$TEMPLATE" >> $GITHUB_ENV
          echo "$DELIMITER" >> $GITHUB_ENV
      - name: Create PR for iOS
        uses: peter-evans/create-pull-request@88bf0de51c7487d91e1abbb4899332e602c58bbf
        id: ios-pr
        with:
          path: ios/
          add-paths: DuckDuckGo.xcodeproj/project.pbxproj
          commit-message: Update BSK with autofill ${{ github.event.release.tag_name }}
          branch: update-bsk-with-autofill-${{ github.event.release.tag_name }}
          title: Update BSK with autofill ${{ github.event.release.tag_name }}
          body: ${{ env.PR_BODY_IOS }}
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}

      - name: Checkout macOS
        uses: actions/checkout@v3
        with:
          repository: duckduckgo/macos-browser
          path: macos/
          ref: develop
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
      - name: Update macOS autofill reference
        env:
          BSK_SHA: ${{ steps.bsk-pr.outputs.pull-request-head-sha }}
        run: |
          node ./autofill/scripts/release/update-apple-device-repo.js 'macos'
      - name: Create macOS PR Body
        env:
          VERSION: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES: ${{ github.event.release.body }}
          ASANA_OUTPUT: ${{ steps.create-asana-tasks.outputs.ASANA_OUTPUT }}
          BSK_PR_URL: ${{ steps.bsk-pr.outputs.pull-request-url }}
        run: |
          TEMPLATE="$(node ./autofill/scripts/release/create-pr-template.js macos)"
          # Creates a randomised delimiter. See https://app.asana.com/0/1199892415909552/1203243297643584/f
          DELIMITER=$(echo $RANDOM | md5sum | head -c 20;)
          echo "PR_BODY_MACOS<<$DELIMITER" >> $GITHUB_ENV
          echo "$TEMPLATE" >> $GITHUB_ENV
          echo "$DELIMITER" >> $GITHUB_ENV
      - name: Create PR for macOS
        uses: peter-evans/create-pull-request@88bf0de51c7487d91e1abbb4899332e602c58bbf
        id: macos-pr
        with:
          path: macos/
          add-paths: DuckDuckGo.xcodeproj/project.pbxproj
          commit-message: Update BSK with autofill ${{ github.event.release.tag_name }}
          branch: update-bsk-with-autofill-${{ github.event.release.tag_name }}
          title: Update BSK with autofill ${{ github.event.release.tag_name }}
          body: ${{ env.PR_BODY_MACOS }}
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}

      - name: Checkout Extensions
        uses: actions/checkout@v3
        with:
          repository: duckduckgo/duckduckgo-privacy-extension
          path: extensions/
          ref: main
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
      - name: Update Extensions autofill reference
        run: |
          cd extensions
          npm install github:duckduckgo/duckduckgo-autofill#${{ github.event.release.tag_name }}
          cd ..
      - name: Create Extensions PR Body
        env:
          VERSION: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES: ${{ github.event.release.body }}
          ASANA_OUTPUT: ${{ steps.create-asana-tasks.outputs.ASANA_OUTPUT }}
        run: |
          TEMPLATE="$(node ./autofill/scripts/release/create-pr-template.js extensions)"
          # Creates a randomised delimiter. See https://app.asana.com/0/1199892415909552/1203243297643584/f
          DELIMITER=$(echo $RANDOM | md5sum | head -c 20;)
          echo "PR_BODY_EXTENSIONS<<$DELIMITER" >> $GITHUB_ENV
          echo "$TEMPLATE" >> $GITHUB_ENV
          echo "$DELIMITER" >> $GITHUB_ENV
      - name: Create PR for Extensions
        uses: peter-evans/create-pull-request@88bf0de51c7487d91e1abbb4899332e602c58bbf
        id: extensions-pr
        with:
          path: extensions/
          add-paths: |
            package.json
            package-lock.json
          commit-message: Update autofill to ${{ github.event.release.tag_name }}
          branch: update-autofill-${{ github.event.release.tag_name }}
          title: Update autofill to ${{ github.event.release.tag_name }}
          body: "${{ env.PR_BODY_EXTENSIONS }}"
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}

      - name: Checkout Windows
        uses: actions/checkout@v3
        with:
          repository: duckduckgo/windows-browser
          path: windows/
          ref: develop
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
      - name: Update Windows autofill reference
        run: |
          cd windows/submodules/duckduckgo-autofill
          git checkout ${{ github.event.release.tag_name }}
          cd ../..
      - name: Create Windows PR Body
        env:
          VERSION: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES: ${{ github.event.release.body }}
          ASANA_OUTPUT: ${{ steps.create-asana-tasks.outputs.ASANA_OUTPUT }}
        run: |
          TEMPLATE="$(node ./autofill/scripts/release/create-pr-template.js windows)"
          # Creates a randomised delimiter. See https://app.asana.com/0/1199892415909552/1203243297643584/f
          DELIMITER=$(echo $RANDOM | md5sum | head -c 20;)
          echo "PR_BODY_WINDOWS<<$DELIMITER" >> $GITHUB_ENV
          echo "$TEMPLATE" >> $GITHUB_ENV
          echo "$DELIMITER" >> $GITHUB_ENV
      - name: Create PR for Windows
        uses: peter-evans/create-pull-request@88bf0de51c7487d91e1abbb4899332e602c58bbf
        id: windows-pr
        with:
          path: windows/
          add-paths: |
            submodules/duckduckgo-autofill
          commit-message: Update autofill to ${{ github.event.release.tag_name }}
          branch: update-autofill-${{ github.event.release.tag_name }}
          title: Update autofill to ${{ github.event.release.tag_name }}
          body: "${{ env.PR_BODY_WINDOWS }}"
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}

      - name: Update Asana tasks
        env:
          ASANA_ACCESS_TOKEN: ${{ secrets.NATIVE_APPS_WORKFLOW }}
          VERSION: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES: ${{ github.event.release.body }}
          ASANA_OUTPUT: ${{ steps.create-asana-tasks.outputs.ASANA_OUTPUT }}
          BSK_PR_URL: ${{ steps.bsk-pr.outputs.pull-request-url }}
          IOS_PR_URL: ${{ steps.ios-pr.outputs.pull-request-url }}
          MACOS_PR_URL: ${{ steps.macos-pr.outputs.pull-request-url }}
          ANDROID_PR_URL: ${{ steps.android-pr.outputs.pull-request-url }}
          WINDOWS_PR_URL: ${{ steps.windows-pr.outputs.pull-request-url }}
          EXTENSIONS_PR_URL: ${{ steps.extensions-pr.outputs.pull-request-url }}
        run:  node ./autofill/scripts/release/asana-update-tasks.js

      - name: Ouput workflow summary
        run: echo "### Success! :rocket:" >> $GITHUB_STEP_SUMMARY
