name: Bundle Size Check

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    bundle-size-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.0.0'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Calculate current bundle size
              id: current-calculation
              run: |
                  echo "current_size_js=$(du -sb dist/autofill.js | cut -f1)" >> $GITHUB_OUTPUT
                  echo "current_size_js_debug=$(du -sb dist/autofill-debug.js | cut -f1)" >> $GITHUB_OUTPUT

            - name: Get base commit and calculate base size
              id: base-calculation
              run: |
                  # Get base commit SHA
                  BASE_SHA="${{ github.event.pull_request.base.sha }}"

                  # Checkout base commit
                  git checkout $BASE_SHA

                  # Install dependencies and build
                  npm ci
                  npm run build

                  # Calculate base size
                  echo "base_size_js=$(du -sb dist/autofill.js | cut -f1)" >> $GITHUB_OUTPUT
                  echo "base_size_js_debug=$(du -sb dist/autofill-debug.js | cut -f1)" >> $GITHUB_OUTPUT

                  # Return to current commit
                  git checkout ${{ github.sha }}
                  npm ci
                  npm run build

            - name: Generate bundle size comment
              id: generate-comment
              run: |
                  # Set environment variables for the script
                  export BASE_SIZE_JS="${{ steps.base-calc.outputs.base_size_js }}"
                  export CURRENT_SIZE_JS="${{ steps.current-size.outputs.current_size_js }}"
                  export BASE_SIZE_JS_DEBUG="${{ steps.base-calc.outputs.base_size_js_debug }}"
                  export CURRENT_SIZE_JS_DEBUG="${{ steps.current-size.outputs.current_size_js_debug }}"

                  # Run the script and capture output
                  npm run bundle-size-check > comment.txt

                  # Read the comment content
                  echo "comment_body<<EOF" >> $GITHUB_OUTPUT
                  cat comment.txt >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            - name: Comment on PR
              uses: actions/github-script@v7
              with:
                  script: |
                      const comment = `${{ steps.generate-comment.outputs.comment_body }}`;

                      await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: comment
                      });
