name: Password Rules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # every morning at 3am UTC

jobs:
  update:
    name: Get latest password rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Get latest rules
        run: node ./packages/password/scripts/rules.js --write-rules-json
      - name: Check for changes
        id: changes
        run: |
          filesChanged=$(sh ./scripts/check-for-changes.sh)
          if [ -z "$filesChanged" ]; then hasChanged="false"; else hasChanged="true"; fi
          echo "hasChanged=$hasChanged" >> "$GITHUB_OUTPUT"
        shell: bash {0}
      - name: Get current date
        id: date
        run: |
          echo "currentDate=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Create PR for updated rules
        if: ${{ steps.changes.outputs.hasChanged == 'true' }}
        uses: peter-evans/create-pull-request@88bf0de51c7487d91e1abbb4899332e602c58bbf
        with:
          add-paths: |
            packages/password/rules.json
          commit-message: Update password rules
          branch: automated/update-password-rules-${{ steps.date.outputs.currentDate }}
          title: "Update password rules (${{steps.date.outputs.currentDate}})"
          body: "Updating password rules from remote source, pulled on ${{steps.date.outputs.currentDate}}"
          token: ${{ secrets.DAXMOBILE_AUTOFILL_AUTOMATION }}
